### ISSUE TITLE
Create approach to either build or fetch pre-built native for sqlite

### ISSUE THREAD

**Issue by pombredanne** [nexB/aboutcode-manager#104]
This requires a build from sources. This may involve reusing builds from #16 and or storing a pre-built node module for each OS as part of #103 
The point is to have stable, controlled and easy to build sqlite binaries without requiring  recurring builds from source. (which in turn requires having a compiler, etc to build the native C code)

**Comment by jdaguil** [comment]
The sqlite issues have been resolved as we are now building Linux and Mac on Travis, and we use AppVeyor for Windows.
