### ISSUE TITLE
Ensure that each build has a new version

### ISSUE THREAD

**Issue by pombredanne** [nexB/aboutcode-manager#106]
To support #16 we need to make sure that each build creates new and unique archives.
For instance in ScanCode the few functions at the top of the setup.py build a new unique version numbers dealing with git commits and status, existing tags and distance from tags: https://github.com/nexB/scancode-toolkit/blob/d3ea42ebdc1c5f09dfaadee568675e82bedce21f/setup.py#L22

We need something similar for ABCMgr (possibly the same code)

Without a unique version number in each arch, we cannot know what a certain build is (e.g. which commit it is for)

**Comment by pombredanne** [comment]
This is not yet on Windows

**Comment by jdaguil** [comment]
Done in 3efb9ef
