### ISSUE TITLE
Add ability to filter components that have Status set to NR

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-manager#117]
See also https://github.com/nexB/aboutcode-manager/issues/116

If a component has the Status set to NR (Not Reporting), provide the ability to filter these components to not show in the Node View tree.

**Comment by jdaguil** [comment]
@majurg When you get a chance can you test this? This iteration has the ability to hide nodes based on status. I anticipate there will be future enhancement issues. One in particular is:
* Show child nodes that should be visible even if ancestor nodes are hidden.

**Comment by majurg** [comment]
@jdaguil Just took some time to test this, here are some thoughts:

- Marking nodes as NR does not make them disappear from the node view when one expands its ancestor node, it simply turns the node white (not sure if this was the intent or not).

- Marking a child node "Needs attention" (or anything NOT `NR`) keeps the child node visible even when its ancestor is marked `NR`

**Comment by jdaguil** [comment]
@majurg do the behaviors you described above still occur when checking the status you would like to hide? For example in the gif below, the NR nodes are hidden when selected in the filter. 

![hide-status2](https://user-images.githubusercontent.com/4239800/30085855-14efd3e4-925e-11e7-8299-5ebaba445c9b.gif)

**Comment by majurg** [comment]
@jdaguil Ah good point I did not catch that. After following your directions:

- Marking nodes `NR` DOES make them disappear from the node view when the correct check-box is selected.

- Marking a child node "Needs attention" (or anything not NR) DOES NOT keep the child node visible when an ancestor is marked NR

An additional comment: maybe consider changing the `Hide Nodes` dropdown to `Node Visibility` or something like that. 

For me, checkboxes signify something is selected and visible, while an un-checked box indicates to me that the particular checkbox item/category is not visible.

**Comment by jdaguil** [comment]
@majurg thanks for testing and feedback! I've switched the behavior to show nodes when checked and hide nodes when unchecked. For:

> Marking a child node "Needs attention" (or anything not NR) DOES NOT keep the child node visible when an ancestor is marked NR

This is a little more complicated to resolve because it requires knowing what every child is doing which will require a db call. So I was planning to add a separate enhancement issue for that so the overall feature wouldn't be held up. Is that ok?

**Comment by majurg** [comment]
@jdaguil Yes, a separate issue is a good idea. The changes look great so far in any case.

**Comment by jdaguil** [comment]
thanks @majurg!
