### ISSUE TITLE
Unable to perform any operation after download

### ISSUE THREAD

**Issue by Sheriff123** [nexB/aboutcode-manager#119]
Hello,
I have downloaded the application onto my computer with Ubuntu installed.When I open the application, i am unable to do File -> Import JSON file, I am also not able to import the JSON file via ctrl + I . Is there any dependency that i need to install to get this working?

Is there any documentation available for this tool apart from the wiki page mentioned below?
https://github.com/nexB/aboutcode-manager/wiki

Thanks in advance

**Comment by pombredanne** [comment]
Thanks for the report! Which exact Ubuntu version and arch are you running? 

At the moment we have some build issues on some OS and OS versions that we are working in fixing before the 2.0x release! 

We are also direly missing some minimal doc and that's also planned for 2.0

**Comment by Sheriff123** [comment]
Hello ,
I have ubuntu 14.04 LTS 64bit installed in my system.
Please Note: I tried with the AboutCode-Manager-linux-x64-v2.0.0-rc1 file download.

**Comment by pombredanne** [comment]
@Sheriff123 ok. This explains it. The current pre-build were done on Ubuntu 16.x and there is no backward compatibility. This is an issue that is worked out currently with #16 
Let me ping you as soon as we have a working build that you can try out. Alternatively you could also give it a shot to building from sources... but this is a tad more engaged.

**Comment by Sheriff123** [comment]
Hello @pombredanne ,
Thanks for the information. I was worried I may be doing some thing wrong from my end. I would surely try to build the sources and check if I am able to get it working. 

Thanks a lot :+1:

**Comment by pombredanne** [comment]
@Sheriff123 ping if you have any problem with building from sources in the meantime.

**Comment by Sheriff123** [comment]
Hi,
 Thanks for your support. Yes I had faced some issues while installing
nodejs because of which electron was getting installed. But later I was
able to rectify it by downloading node v6.6.0 and setting it with default
path after which i was able to find the electron-rebuild.

I find the tool very much useful. But i am curious to know if there is
possibility to create a database and add the data to database. If so it
would be easier for many enthusiastic to add the data to server which can
be used inturn to build the databse and use for finding open source match
when we upload the sources.

Thanks once again 😀

On 08-Jul-2017 8:56 PM, "Philippe Ombredanne" <notifications@github.com>
wrote:

@Sheriff123 <https://github.com/sheriff123> ping if you have any problem
with building from sources in the meantime.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nexB/aboutcode-manager/issues/119#issuecomment-313862742>,
or mute the thread

**Comment by jdaguil** [comment]
> i am curious to know if there is  possibility to create a database and add the data to database. If so it would be easier for many enthusiastic to add the data to server which can be used inturn to build the databse and use for finding open source match when we upload the sources.

@Sheriff123 Sorry, I'm not sure I understand your question. We do create a (SQLite) database when you import a JSON file, but I'm not sure if that helps since I don't understand your use case. Please feel free to clarify if this doesn't answer your question.

**Comment by mjherzog** [comment]
The SQLite database used in AbC Manager is only intended for use in AbC Manager - it is not intended to be a standalone database for scans or for conclusions. We are working on some ideas for multi-user server/database support for AboutCode overall, but this would require new server and database infrastructure.
