### ISSUE TITLE
Add user OS supported for installation in documentation

### ISSUE THREAD

**Issue by pombredanne** [nexB/aboutcode-manager#120]
The base OS supported:

    Win7 64-bit and up (no 32 bits for now)
    macOS 10.9 64-bit and up
    Linux 64-bit on Ubuntu 12.04 and up (TBD Debian/Fedora/CentOS support) (no 32 bits support)

**Comment by johnmhoran** [comment]
This is now addressed in the wiki (https://github.com/nexB/aboutcode-manager/wiki/Platform-Support).
