### ISSUE TITLE
Setup a place where builds can be staged and uploaded after a CI run

### ISSUE THREAD

**Issue by pombredanne** [nexB/aboutcode-manager#122]
We need to store the build on each commit. The CI do not allow to download the built artifacts but only allow these to be uploaded instead. The volume is about 200MB per commit so we need quickly to have a few GB on hand for this task. (And could purge some commit build often enough)
- Bintray could be an option but is somewhat convoluted and limited to 500MB for the free tier
- other options
  - a dedicated server where we SSH an expose a plain file directory
  - S3

**Comment by jdaguil** [comment]
This is done. See https://github.com/nexB/aboutcode-manager/issues/16#issuecomment-321270569
