### ISSUE TITLE
Change descriptions of Save and Export functions

### ISSUE THREAD

**Issue by johnmhoran** [nexB/aboutcode-manager#126]
Two possible modifications to the dropdowns in the File menu:
  * Change `Save SQLite File` to `Save SQLite File As New File` (this assumes it's actually a "save-as" rather than a traditional "save" function).
  * Change `Export JSON File` to `Export SQLite File to JSON`.

**Comment by jdaguil** [comment]
- I think `Export JSON File` is ok as is. I don't think the user needs to know about the default save when choosing to export a JSON file.  
- I'd suggest `Change Save SQLite File` to `Save As New SQLite File`
