### ISSUE TITLE
Add links in Component Summary View

### ISSUE THREAD

**Issue by johnmhoran** [nexB/aboutcode-manager#128]
If you don’t recall where you’ve created a Component, you can go to Component Summary View and see the list.  However, you cannot navigate to a Component directly from that list and instead need to use the tree to find the file/directory with the Component you're looking for.  Would users find it handy if we could provide links directly from the Component Summary View to each listed Component?

**Comment by mjherzog** [comment]
Changed to Should Have. This will be an important new feature in the near term.

**Comment by jdaguil** [comment]
The implementation of this should be similar to what we did for the URL links in the tables https://github.com/nexB/aboutcode-manager/blob/e6686c0358dc8536305d9c38e3bbc0ed4ad90f5e/assets/app/js/helpers/utils.js#L13
In particular, we add an onClick to the html element surround the text.  As a side note, we might want to consider having the jsTree displayed in all of the views. This might mitigate part of the problem.

**Comment by johnmhoran** [comment]
This issue has been superseded by issue #270.
