### ISSUE TITLE
Fix Bootstrap grid collapse when screen is too narrow

### ISSUE THREAD

**Issue by johnmhoran** [nexB/aboutcode-manager#143]
When the Tree and Table/Node views are displayed and the screen width falls below approximately 990px, the Table/Node view drops out of sight.  This is a result of the Bootstrap grid system, which we use for our layout, responding to the decreased screen width and stacking the three columns that make up our grid row.

From a user's point of view, it might be preferable to replace the grid stacking with a horizontal scrollbar that appears when the screen is sufficiently narrow, while keeping the three columns as one single row.  Perhaps this could be accomplished by modifying the Bootstrap grid CSS; and if not, a set of three divs with `floats` seems likely to provide a solution.

**Comment by jdaguil** [comment]
This has been fixed in https://github.com/nexB/aboutcode-manager/issues/148
