### ISSUE TITLE
Add menu item for Chart Summary View

### ISSUE THREAD

**Issue by johnmhoran** [nexB/aboutcode-manager#144]
*  We'll add as a sub-item to the `View` menu item.
*  Re keyboard shortcuts, `Ctrl+C`, `Ctrl+Shift+C`, `Ctrl+S` and `Ctrl+V` (among others) are already being used.  Suggestions are welcome!

**Comment by johnmhoran** [comment]
Subject to ideas for a more intuitive combo, I’m planning to use `Ctrl+Shift+V` as the keyboard shortcut -- "V" for "visualization" (`Ctrl+V` is already used for paste).  Our current `View` menu items:

![image](https://user-images.githubusercontent.com/11096678/28978961-e1b84c6a-78fc-11e7-80a2-04cf2834ffa9.png)

**Comment by johnmhoran** [comment]
For some reason `Ctrl+Shift+V` does not work.  No errors but no response.  I see no conflicts in our code, and the [Electron documentation](https://electron.atom.io/docs/all/#available-key-codes) suggests this option is available.  `Ctrl+Shift+Z` does work, so at least for now I'll use that.

**Comment by johnmhoran** [comment]
Correction: `Ctrl+Shift+Z` is already taken.

**Comment by jdaguil** [comment]
Merged into `develop`
