### ISSUE TITLE
Update wiki to document Chart Summary View

### ISSUE THREAD

**Issue by johnmhoran** [nexB/aboutcode-manager#145]

**Comment by johnmhoran** [comment]
@jdaguil -- I think we may be finished with this issue.  If you agree, please let me know and I'll close.

**Comment by jdaguil** [comment]
@johnmhoran Yes, [Navigating the Chart Summary View](https://github.com/nexB/aboutcode-manager/wiki/Navigating-the-Chart-Summary-View) looks good. We can close this.
