### ISSUE TITLE
Refactor HTML and CSS

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-manager#148]
We haven't looked at the HTML and CSS in awhile. There are a lot of things that can be cleaned up or removed to simplify the HTML, CSS, and JS.

**Comment by jdaguil** [comment]
@johnmhoran can you test for usability on Windows and Linux when you get a chance?

**Comment by johnmhoran** [comment]
@jdaguil  Absolutely -- will do so in a little while and report back.

**Comment by johnmhoran** [comment]
@jdaguil  Comments from Windows 10:

*  Overall, this looks great.  Among other things, the way the Table View’s DataTable fits neatly on the screen makes navigation easier and looks tight and desktop-app-like.  And it resizes as the screen resizes.  Nice.  The new jsTree background also offsets the Tree View more distinctly from the Table, Node and Chart Summary Views.
* Big thumbs-up for the brighter, more visible sidebar icons.
* One thing I noticed: in the Node View, the branches from parent to child nodes are thicker.  
  * Compare the #148 version:
![image](https://user-images.githubusercontent.com/11096678/29048595-6cbbe26e-7b86-11e7-9684-5a6799f63402.png)
  * and the version on `develop`:
![image](https://user-images.githubusercontent.com/11096678/29048606-774d41dc-7b86-11e7-9742-2e7ddd44ca23.png)

**Comment by jdaguil** [comment]
@johnmhoran thanks, will look into the branch thinkness :)

**Comment by johnmhoran** [comment]
@jdaguil  Same look, feel and performance on Ubuntu 16.04 as on Windows 10 -- very nice!

**Comment by jdaguil** [comment]
@johnmhoran The css for the node view branches has been added back.

**Comment by johnmhoran** [comment]
@jdaguil Just pulled and ran on both Windows 10 and Ubuntu 16.04 -- looks good!

**Comment by jdaguil** [comment]
@johnmhoran thanks! 😄

**Comment by johnmhoran** [comment]
@jdaguil  One other thought -- perhaps drop the node branch thickness from 2px to 1px?  

Current 2px (#ccc;):

![image](https://user-images.githubusercontent.com/11096678/29052077-6674c1f8-7b9c-11e7-876e-2998054923ed.png)

1px (#ccc;):

![image](https://user-images.githubusercontent.com/11096678/29052081-6daf3cf0-7b9c-11e7-859f-ab3c19e9321a.png)

1px, darker line (#333333;):

![image](https://user-images.githubusercontent.com/11096678/29052135-cfe20ede-7b9c-11e7-846a-7aa7155bf486.png)

**Comment by jdaguil** [comment]
IMHO the third one (#333333) seems too dark. The second one (#ccc) looks ok on my laptop screen, but too light on my monitor. I think we should stick with the current styling.
