### ISSUE TITLE
File and package information are needed for the node view of the app

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-manager#15]
Currently, the file/package info is needed for the the node view so that we know which entries are files and which are directories. For now, users must scan for file and package info.

We could eventually try to implement a "best guess" using the location path, but it would get tricky to ensure whether something is file/directory just based off of the name. We need to address this.

**Comment by jdaguil** [comment]
I don’t think best guess will be good enough in most cases. Solutions I have are: 

- Enforce file information included in the scan (which is what we do now)
- Always return the file type (file or directory). This is a change that would need to be made in ScanCode https://github.com/nexB/scancode-toolkit/issues/802

**Comment by majurg** [comment]
This may be able to be closed, as we have decided to sunset the Node view. Thus new feature requests + additions are probably not going to make it in.

**Comment by majurg** [comment]
Per #255, the Node View has been depreciated. Closing this ticket.
