### ISSUE TITLE
Fix bar chart and node view to display when view is loaded

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-manager#152]
When switching to these views no visual is initially shown until the tree is selected.

**Comment by jdaguil** [comment]
@johnmhoran:

> ### How is the root node created from a scan with no root node?

This is where we create the root node.
https://github.com/nexB/aboutcode-manager/blob/e15d2023b4400cecef6aac2e6b711618a867db3f/assets/js/renderer.js#L617-L618
 

> ### How is the Table View populated on load as if the root node had been selected?

Whenever the DataTable is first created, the first thing it's going to do is try is load some data. The DataTable `ajax` option defines how the DataTable gets its data. https://github.com/nexB/aboutcode-manager/blob/e15d2023b4400cecef6aac2e6b711618a867db3f/assets/js/aboutCodeDataTables.js#L159-L160  In our case, it just calls the query function. https://github.com/nexB/aboutcode-manager/blob/e15d2023b4400cecef6aac2e6b711618a867db3f/assets/js/aboutCodeDataTables.js#L45-L47 This is the query we are trying to build: https://github.com/nexB/aboutcode-manager/blob/e15d2023b4400cecef6aac2e6b711618a867db3f/assets/js/aboutCodeDataTables.js#L54-L65
Filtering on the jstree is essentially this line:
https://github.com/nexB/aboutcode-manager/blob/e15d2023b4400cecef6aac2e6b711618a867db3f/assets/js/aboutCodeDataTables.js#L57
When a file is first loaded, the `columnSearch` for the path column is empty, so no filtering is done (which means all rows are shown) https://github.com/nexB/aboutcode-manager/blob/e15d2023b4400cecef6aac2e6b711618a867db3f/assets/js/aboutCodeDataTables.js#L79

> ### Where are the corresponding hooks for the Node and Chart Views?

Changing the node view and the chart view to display data when nothing is selected in the jstree is one way to fix this, but I think it would be better to just select the root element in the jstree when a file is first loaded. The reason I think this would be better is because we can reuse the same logic that is applied when the user selects the jstree.
https://github.com/nexB/aboutcode-manager/blob/e15d2023b4400cecef6aac2e6b711618a867db3f/assets/js/renderer.js#L91-L98 Also, I think it’s more intuitive to show the data that is selected by the jstree rather than showing default data when nothing is selected. 

I think what you want to focus on is selecting the first element in the jstree whenever the jstree is updated. In our code, this happens by refreshing the jstree in renderer.js here: 
https://github.com/nexB/aboutcode-manager/blob/e15d2023b4400cecef6aac2e6b711618a867db3f/assets/js/renderer.js#L521-L522 

Therefore, you can listen for jstree refresh events 
https://www.jstree.com/api/#/?q=.jstree%20Event&f=refresh.jstree
And try to select the first jstree element in that callback, similar to how we handle other events:
https://github.com/nexB/aboutcode-manager/blob/e15d2023b4400cecef6aac2e6b711618a867db3f/assets/js/renderer.js#L91-L98

**Comment by johnmhoran** [comment]
Thanks very much, @jdaguil !
