### ISSUE TITLE
Hang on the "Creating Database ..." when trying to replace the existing DB

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-manager#156]
1. Import a JSON file
2. Then asked to save to a SQLite DB file
3. Choose an existence SQLite DB file
4. Confirmed to overwrite/replace

After clicked the `Yes` button to confirm, the ABC Manager hangs in the "Creating Database ..."

**Comment by jdaguil** [comment]
@chinyeungli Which version are you using? Is this at the head of `develop` or a release candidate?

**Comment by chinyeungli** [comment]
@jdaguil I'm using `AboutCode-Manager-win32-x64-v2.0.0-rc3`

**Comment by jdaguil** [comment]
The fix has been merged into `develop` and is in [v2.0.0-rc5](https://github.com/nexB/aboutcode-manager/releases/tag/v2.0.0-rc5).
