### ISSUE TITLE
Column visibility buttons should include the option to 'select none'

### ISSUE THREAD

**Issue by majurg** [nexB/aboutcode-manager#158]
Slightly related to #3: ABCM should let the user select no columns or allow the user clear the current column visibility. 

Many times when filtering results, I have to de-select the various columns I do not care for in order to see the relevant data. This is tedious, especially when changing views or accidentally hitting another column view mode. 

A simple button that says 'Select None' or 'Clear Columns' or 'No Columns' would suffice and make things a lot easier.

**Comment by jdaguil** [comment]
Good idea @majurg. I'm thinking we should always keep the **Path** column shown though.

**Comment by majurg** [comment]
@jdaguil yes the path column should always be there, good point.
