### ISSUE TITLE
DataTable filters should have a 'Non-Blank' option

### ISSUE THREAD

**Issue by majurg** [nexB/aboutcode-manager#159]
I find myself using filters a lot when looking for license+copyright clues. The filters themselves work great, but I also find myself having to filter thru each listed value to analyze all the rows that have a value in the `license` column, for example. 

In almost all cases, I simply want to see all the rows where a particular column's value is 'Non-Blank'

When listing it in the filter selection popup, you could show it as ((Non-Blank)) or ((Has A Value)) to distinguish it from the rest of the possible filter values.

**Comment by jdaguil** [comment]
@majurg I have added **Has a Value** to the drop down menu as the first value. Does this work for now? In the future, I can plan to add some additional styling to further distinguish this filter.

**Comment by majurg** [comment]
@jdaguil Yes, that is perfect. Just tested it out on the branch and it look and works great :+1:
