### ISSUE TITLE
Create installable builds for Linux, macOSX and Windows (e.g. Setup Travis and Appveyor CI/builds)

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-manager#16]
We need to setup for now a build (tests will come later) such that we can have as an end result an installable archive for each OS.
1. check with Travis that we have macOs enabled
2. create a build script that only builds each of Linux, macOS and Windows respectively
3. setup the travis and appevyor yaml to build and make available the results for download

**Comment by pombredanne** [comment]
A key part of the build is to be able to upload somewhere the final built apps.

For Appveyor this is something I worked out here:
- https://github.com/pombreda/thirdparty/blob/e9f593bdaa1e51ea0a514c8df643ef0371e69e30/appveyor.yml#L37
-  this uploads to bintray basically anything that is in this directory: https://github.com/pombreda/thirdparty/blob/e9f593bdaa1e51ea0a514c8df643ef0371e69e30/appveyor.yml#L34

For Travis, the part for uploading is there:
- https://github.com/pombreda/thirdparty/blob/e9f593bdaa1e51ea0a514c8df643ef0371e69e30/.travis.yml#L56
- and this use this JSON file to upload anything in the wheels directory https://github.com/pombreda/thirdparty/blob/e9f593bdaa1e51ea0a514c8df643ef0371e69e30/bintray_travis.json

There may be other ways, but I am not sure that it is worth it: For instance appveyor has a link to the latest build "artifact": https://www.appveyor.com/docs/packaging-artifacts/ .... but only the latest. Hence the need to publish it somewhere instead. The builds could be published to Github too btw, but this would need a tad work https://www.appveyor.com/docs/deployment/github/ and this would mean basically having a tag on each build


The ref docs for travis are there: https://docs.travis-ci.com/user/deployment/




We need though to define a proper scheme for versions as each built version should be unique (e.g. reference the commit)

**Comment by johnmhoran** [comment]
Yesterday's commit https://github.com/nexB/aboutcode-manager/commit/58f9a82ac469b25682a5ebc455b7c56368af7830 contains my initial draft `appveyor.yml`.  The push triggered AppVeyor build 216 (https://ci.appveyor.com/project/nexB/aboutcode-manager/build/216).

* Seemed to install OK including `sqlite3`.
* The build installed `npm 3.10.10` and `node 6.11.0`.
* Exited with code 1 on line 1735.
* Failed upon running `python build.py`.  The failure block:
```
python build.py
=> BUILDING AboutCode App release: 2.0.0
Traceback (most recent call last):
  File "build.py", line 221, in <module>
    build()
  File "build.py", line 167, in build
    shutil.rmtree(build_dir)
  File "C:\Python27\lib\shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "C:\Python27\lib\shutil.py", line 237, in rmtree
    names = os.listdir(path)
WindowsError: [Error 3] The system cannot find the path specified: u'dist\\*.*'
Command exited with code 1
```
* This is similar, but not identical, to the error I encountered running locally on Windows 10.  The AppVeyor error seems to say the path to the `dist` directory can’t be found, reminiscent of my initial Ubuntu 16.04 error, where the `dist` directory in fact did not exist.  However, examining our code tree in Git Bash as well as Visual Studio Code, I see that a `dist` directory already exists.
* The initial `appveyor.yml` file:
```
version: '{build}'

image: Visual Studio 2017

# Test against the latest version of this Node.js version
# environment:
#   nodejs_version: "6"

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'

init:
  - git config --global core.autocrlf input

# Install scripts (runs after repo cloning)
install:
  - ps: Install-Product node 6 x64
  # - git reset --hard HEAD
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - python build.py

test: off
```

**Comment by pombredanne** [comment]
At this stage we have a proper build that is done on Windows and that creates some archive 
@jdaguil contacted Travis to enable mac.
The build is failing on Linux with the `npm bin` command (with shell=True) and is failing  on mac because of apt-get calls.

**Comment by pombredanne** [comment]
We now have the build running on all three OSses and producing some archive. Next we need to upload them somewhere so that we can test them. I will also add a SHA1 and SHA256 checksum such that these uploads can be verified.

**Comment by jdaguil** [comment]
The application that is created from the new script is now working on Mac. Linux and Windows still need to be tested and verified.

**Comment by johnmhoran** [comment]
Testing on Windows 10, the application created by running `python build.py` (in the Windows command prompt) seems to work well.  

With my current setup, this requires:
* checking out branch 16 in Git Bash, 
* running `git pull` to update, 
* opening the Windows command prompt, 
* navigating to the `aboutcode-manager` directory 
  * note that the command prompt does not reflect which branch is currently checked out -- running `git status`, for example, produces `'git' is not recognized as an internal or external command, operable program or batch file`-- Git Bash does that work
* running `python build.py`.

When I ran `python build.py` in Git Bash, the result was this:
```
Tue Jul 11, 2017 10:01 AM  /c/code/nexb/dev/aboutcode-manager JMH (16-python-build-script)
$ python build.py

=> BUILDING AboutCode App release: 2.0.0
    platform: Windows-10-10.0.15063 sys.platform: win32
Traceback (most recent call last):
  File "build.py", line 243, in <module>
    build()
  File "build.py", line 179, in build
    os.makedirs(build_dir)
  File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 5] Access is denied: u'dist'
```

**Comment by johnmhoran** [comment]
The application created by running `python build.py` seems to work well on Ubuntu 16.04.

**Comment by pombredanne** [comment]
I started to have at least some downloads pushed for Mac and Linux from Travis.
Here are some quick notes:
```
Project at sf:
https://sourceforge.net/projects/aboutcode-manager/

User with "SCP" right (aka "release technician")
https://sourceforge.net/u/aboutcode-rel/

I generated a dedicated SSH key pair with
ssh-keygen -t rsa -C "aboutcode-rel@shell.sf.net
and asked it to be sored in the root dir of the ABCM checkout

This par of keys was created (I named them this):
deploy_rsa
deploy_rsa.pub


I then installed travis globally
This is a pain.

$ travis login
$ travis encrypt-file deploy_rsa --add

This created deploy_rsa.enc and updated the travis.yml (and damaged it a bit along the way) with:
  - openssl aes-256-cbc -K $encrypted_906d16ae5679_key -iv $encrypted_906d16ae5679_iv -in deploy_rsa.enc -out deploy_rsa -d


I then fixed the travis script


I also tested the SCP with this:
scp -i deploy_rsa aboutcode.ABOUT  aboutcode-rel@web.sourceforge.net:/home/frs/project/aboutcode-manager/builds/


We updated the Travis script and bingo:
https://sourceforge.net/projects/aboutcode-manager/files/builds/

Issues:
- version/name of the build is not correct: git fails
- we need to compute a sha1

```

**Comment by pombredanne** [comment]
ATM on Linux, I get this error: `Uncaught Error: Please install sqlite3 package manually` ... so we are getting there!

**Comment by pombredanne** [comment]
This is for a build I fetched from sf.net

**Comment by pombredanne** [comment]
We still have one issues in that the build does not run yet properly on Mac... 
We are getting `make: g++-4.8: No such file or directory`

**Comment by pombredanne** [comment]
At this stage all OS do build:
- Linux and Mac are uploaded to https://sourceforge.net/projects/aboutcode-manager/files/builds/
- Windows appveyor handles this through Artifact for each build: For instance this contains the latest build download https://ci.appveyor.com/project/nexB/aboutcode-manager/build/artifacts

@jdaguil the mac build needs to be verified for sanity
@johnmhoran same for the linux build 

The upload takes place on EVERY commit and we may want to limit this to tags only for sanity?

**Comment by jdaguil** [comment]
@pombredanne will do. And I agree I think we should limit to tags.

**Comment by jdaguil** [comment]
I am having issues with the mac build from sourceforge:

1. When first extracted, I am prompted with the following message: <img width="423" alt="screen shot 2017-08-09 at 8 48 48 am" src="https://user-images.githubusercontent.com/4239800/29135408-dd1c59d0-7cee-11e7-9682-6c9dc797fe1f.png">

2.  After I go to system preferences and change the settings from *Mac App Store and identified developers* to *Anywhere* I have to re-extract the archive to get the error message in (1) to go away.  The above error message persists with the initial extracted archive even after preferences are changed.
3. I then get another error message: <img width="427" alt="screen shot 2017-08-09 at 8 52 28 am" src="https://user-images.githubusercontent.com/4239800/29135492-281ea69a-7cef-11e7-907f-4e9e996755ef.png">

OS Details:
```bash
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin15.6.0
Thread model: posix

usr/bin/xcodebuild -version
Xcode 6.1.1
Build version 6A2008a

```

**Comment by jdaguil** [comment]
I am also having issues running the `build.py` script locally. At https://github.com/nexB/aboutcode-manager/issues/16#ref-commit-9858320 I was able to run the script and produce a working app. Now the the script will not run locally, and I get the following error: 
```bash
$ build.py 
DEBUG: get_version: tag: 2.0.0-rc3 distance: 112 commit: f858339 dirty: False
DEBUG: get_version: dirty, using timestamp: 2.0.0-rc3.post112.f858339

#############################################################
=> BUILDING AboutCode App release: 2.0.0-rc3.post112.f858339
platform: Darwin-15.6.0-x86_64-i386-64bit sys.platform: darwin
using NPM bin at: /aboutcode-manager/node_modules/.bin
Running electron-rebuild...
Running command: u'/aboutcode-manager/node_modules/.bin/electron-rebuild'...
✔ Rebuild Complete
Running electron-packager...
Running command: u'/aboutcode-manager/node_modules/.bin/electron-packager . AboutCode-Manager --prune --ignore=thirdparty/* --ignore=dist/* --ignore=/\\.idea --ignore=/\\.gitignore --ignore=/test --ignore=/tmp --ignore=/bower.json --platform=darwin --arch=x64 --icon=assets/app-icon/mac/aboutcode.icns --version=1.4.0 --out=dist --asar=true --overwrite=true'...
Packaging app for platform darwin x64 using electron v1.4.0
Command failed: npm prune --production
npm ERR! May not delete: /private/var/folders/6d/7nz7bkx92n38xwc2frhqrsjm0000gn/T/electron-packager/darwin-x64/AboutCode-Manager-darwin-x64/Electron.app/Contents/Resources/app/node_modules/.bin

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jilliandaguil/.npm/_logs/2017-08-09T17_49_17_717Z-debug.log


Failed to execute command:
u'/aboutcode-manager/node_modules/.bin/electron-packager . AboutCode-Manager --prune --ignore=thirdparty/* --ignore=dist/* --ignore=/\\.idea --ignore=/\\.gitignore --ignore=/test --ignore=/tmp --ignore=/bower.json --platform=darwin --arch=x64 --icon=assets/app-icon/mac/aboutcode.icns --version=1.4.0 --out=dist --asar=true --overwrite=true'
Aborting...
```

**Comment by jdaguil** [comment]
@pombredanne Changing my local version of `npm` to **5.2.0** fixed the issue in https://github.com/nexB/aboutcode-manager/issues/16#issuecomment-321332090. For reference see, https://github.com/npm/npm/issues/17781

**Comment by jdaguil** [comment]
@pombredanne Regarding https://github.com/nexB/aboutcode-manager/issues/16#issuecomment-321329244, latest work in a229cfa resolves the issue when downloading the built archive from sourceforge. However, now the following message is displayed when trying to open the app:
<img width="425" alt="screen shot 2017-08-16 at 4 45 19 pm" src="https://user-images.githubusercontent.com/4239800/29390090-f88757ec-82a2-11e7-8010-090b1b67920f.png">
The app is functional if one of the following steps is taken:

- Security preferences are changed _or_
- Right click on the app and click **Open**

**Comment by johnmhoran** [comment]
@pombredanne @jdaguil  Just a note re a temporary build failure when working a few minutes ago in issue #154 -- [see my comment](https://github.com/nexB/aboutcode-manager/pull/155#issuecomment-323203316).

**Comment by pombredanne** [comment]
@jdaguil FWIW, here are somoe pointers for the macOS issue that are likely related: 
- https://github.com/travis-ci/travis-ci/issues/6935 and https://github.com/travis-ci/travis-ci/issues/7065
- https://github.com/Daemon-Devarshi/MedicationSchedulerSwift3.0/issues/10
- https://developer.apple.com/support/certificates/expiration/
There are likely other sources of details that would matter to us.

**Comment by mjherzog** [comment]
I support the idea that we get the iCloud app certificate assuming that we can use it at the project level.
