### ISSUE TITLE
Add drill-down from Chart Summary Views

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#167]
There are many cases where you will want to click on a bar in the Chart Summary View and see the subset of Paths that comprise that bar.   The best way to present this may be to show the data subset in the Table View with a focus on the Table data columns directly related to the Copyright or License Summary bar. 

You can currently get this data from filters in the Table View, but this approach would be fewer steps and particularly useful for Copyrights or Licenses with smaller data subsets.

**Comment by jdaguil** [comment]
@mjherzog If you click the y-axis label or the bar, the data subset that comprise that bar are shown in the Table View. This also works if the column was originally hidden in the Table View.

**Comment by jdaguil** [comment]
Merged into `develop`
