### ISSUE TITLE
Indicate visually the group button that is chosen

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-manager#17]
In the table view, when a button such as **Copyright Info** , is selected there is no visual indicator that the button has been selected; therefore, it's not obvious which column groups are being filtered in the view.

**Comment by johnmhoran** [comment]
@jdaguil  I just took a look at these group buttons.  It's clear that there's a relationship between the first button -- "Column visibility" -- and the other four buttons, but it's not entirely clear how these are meant to be used.  Let's discuss whenever it's convenient for you.

**Comment by jdaguil** [comment]
The states aren't meant to be static. That is, once you click on a group you can hide some columns and show some columns; therefore, it's no longer the "original" group that was selected. One alternative to how it works now is to have the state of the groups be dynamic. That is, if a group is selected and a column is hidden or shown, that change is reflected in the state of the group so that the next time the group is clicked those changes will be applied. For now, I am going to close this.
