### ISSUE TITLE
Do not assume that files are a set of unique paths when importing a scan

### ISSUE THREAD

**Issue by pombredanne** [nexB/aboutcode-manager#177]
While ScanCode should not return multiple files items with the same path, there is no warranty that this is the case. So I think we should not rely on file paths to be unique. Instead we should accept duplication and merge records and possibly raise errors/warnings if the file records with the same path  are for different things such as the same path but different sizes, checksums, etc

**Comment by jdaguil** [comment]
@pombredanne Is there a reason for ScanCode to not guarantee that all file paths will be unique?

I'm worried that allowing duplicate paths will become an untenable solution.

If ScanCode does not give a guarantee that file paths are unique, then it pushes the burden of interpreting duplicate paths on every consumer of that data. Thus, each consumer has to then document how it handles duplicate paths -- of which there can be multiple valid ways to handle it (e.g. use first and ignore second, ignore first and use second, merge first and second overwriting inconsistencies in first, merge first and second and validate inconsistencies (e.g. sizes, checksums) throwing errors if invalid, etc...)

Thus, to avoid the case where each tool has it's own interpretation for duplicate paths, we would need to explicitly state (somewhere) what the rules are for duplicate paths. However, once those rules are defined, then why wouldn't we just apply those rules in ScanCode such that ScanCode handles duplicates (if for some reason there are duplicates) and ensures that all paths are unique before returning the data.

WDYT?

**Comment by pombredanne** [comment]
There is no reason for dupe paths I can fathom... yet there is no tests for this either and no guarantee either in the ABC data, though we could make it part of the spec.
In general you could for now assume that each path is unique but this comes with some caveats and if there is a test I can find to ensure this I will for sure. Can you enter a a ScanCode ticket ?

**Comment by jdaguil** [comment]
Sounds good! I agree that we should add it to the spec 👍.

**Comment by jdaguil** [comment]
Closing. See also: https://github.com/nexB/scancode-toolkit/issues/807#issuecomment-337590573
