### ISSUE TITLE
Incorrect dialog error message thrown when trying to overwrite an existing sqlite file

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-manager#178]
When a user tries to overwrite a sqlite file, the following dialog message appears:

> The files in the ScanCode output should have unique path values. The following path values were not unique:

This error message is incorrect. 
The Sequelize error is: `SequelizeUniqueConstraintError`

**Comment by johnmhoran** [comment]
@jdaguil  This sounds somewhat similar to the behavior described in issue #156.

**Comment by jdaguil** [comment]
Merged into `develop`
