### ISSUE TITLE
Report count for filter results

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#179]
When you filter results from the Table View, you often have many pages of data returned - may be 10s of pages. It would be very helpful for ABC Manager to display the count for rows returned from the filter - perhaps on the bottom of the page to the left of the page "boxes".  

One could currently estimate this number of rows returned by multiplying the rows displayed per page by the number of pages, but that will be a very rough estimate since the row height varies according to how much data is displayed for the row and column set.

**Comment by jdaguil** [comment]
The info flag was previously set to false for DataTables. The filtered data information will now be shown underneath the table data to the left of the page boxes.
