### ISSUE TITLE
Display name of SQLite file

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#185]
It would be helpful to have a quick reminder of the name of the current (SQLite) file under review in somewhere in the footer or header (as in Office apps).

**Comment by jdaguil** [comment]
@johnmhoran Here's an example of how this could be done.

<img width="1010" alt="filename-header" src="https://user-images.githubusercontent.com/4239800/33393356-c84804e8-d4f3-11e7-8a40-2dd6d3dae894.png">

We could start with just the file name in the header.

**Comment by johnmhoran** [comment]
@jdaguil  I like it.  MS Word has something similar -- it's definitely handy info.  I'm digging into the code now to see where we might add this.  Initial googling of no avail, but seems vaguely menu-related at first blush.
