### ISSUE TITLE
About AboutCodeManager new window is confusing

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#186]
When you click on Help / About AboutCode Manager it opens a new Window with a copy of the full top menu bar. This is confusing because you the File, Edit and half of the View functions are inoperable.  For View you can invoke Reload, Toggle Screen or Toggle Developer Tools. The Window and Help functions work.

I can see a possible future value in opening a second window for Help functions if those Help functions were in-app, but these are currently all links that open in a separate browser tab.

It may be best to remove the About AboutCode Manager menu item and just keep the version displayed below the About item.

**Comment by johnmhoran** [comment]
@jdaguil  @mjherzog  I've resolved this issue by deleting the `About...` menu item and retaining the version info as suggested.  

I see that another item under `Help` also opens an Electron window with the full ABCM top menu: the `Licensing Information` item, which opens the file `attribution.html`.  Do we want to remove the entire top menu from this Electron window?  Display just a subset of the top menu (assuming it's feasible)?  Leave it as is for now?

**Comment by mjherzog** [comment]
I think that opening a second window with menu options is confusing here especially since most of the menu items do not work.  We really just need a way to display the ABCM version number.  I recall that Jillian said displaying the Version is somehow built-in with Electron.  It would be nice for it to say "AboutCode Manager Version x.y", but we can live with just Version x.y for the near future.

**Comment by johnmhoran** [comment]
I just made that change: it now says `AboutCode Manager Version 2.1.0`.

**Comment by johnmhoran** [comment]
@jdaguil  @mjherzog  Re the `Licensing Information` item, I'm now able to remove the top menu from the new window that opens when this item is selected.  

Note that with or without the top menu, among other things there seems to be no way to print from that window, and no way to select all except by dragging the mouse from top to bottom (or vice-versa).

@jdaguil   I'm going to go ahead and test and if OK commit and push -- but I won't open a PR until you give me the go-ahead.  Although it's not defined as part of this issue, I'll include removing the top menu from the `Licensing Information` menu item as part of this commit -- can easily reverse if you prefer.

**Comment by jdaguil** [comment]
@johnmhoran Yes, one with the menu and also one with your updated changes.

**Comment by johnmhoran** [comment]
@jdaguil Here's the revised version (prior version to come shortly):

![image](https://user-images.githubusercontent.com/11096678/33387286-b771f974-d4e1-11e7-9cc9-737a8176b735.png)

**Comment by johnmhoran** [comment]
@jdaguil This is the prior version (on Windows 10):

![image](https://user-images.githubusercontent.com/11096678/33387452-2c530634-d4e2-11e7-9512-06df915d5637.png)

**Comment by jdaguil** [comment]
Thanks @johnmhoran! LGTM! 👍 Feel free to open a PR.
