### ISSUE TITLE
License Reference URL opens up in AboutCode Manager and does not show up well 

### ISSUE THREAD

**Issue by pombredanne** [nexB/aboutcode-manager#187]
This has been verified with the latest 2.0.0 release (and also in previous RC) on Linux and Windows.... so it does not seem to be OS specific.

I load a scan and click on the reference_url in the table view to open a DejaCode link.
The page displays, but no content can been seen.
See attached screenshot
![screenshot from 2017-10-26 20 30 02](https://user-images.githubusercontent.com/675997/32070520-f237dc50-ba8c-11e7-9268-ed42014baf93.png)

**Comment by pombredanne** [comment]
My suggestion may be to use the external, system browser spawned in a new windows to open external URLs rather than using the built-in chromium for these. 
Note that the errors seen in the console are the not exactly the same on Windows and Linux. This is a screen from from Linux
![screenshot from 2017-10-26 20 35 50](https://user-images.githubusercontent.com/675997/32070647-5614433a-ba8d-11e7-99cb-6cc608a81b7b.png)

**Comment by jdaguil** [comment]
This has been fixed and merged into `develop`. URLs will now open in the default browser. Thanks for the report!

**Comment by pombredanne** [comment]
Thanks. Let me test this

**Comment by pombredanne** [comment]
I tested AboutCode-Manager-linux-x64-2.0.0.post3.8ec4d5e on Linux and it works great!.
Thank you.
