### ISSUE TITLE
Support JSON stream to enable import of large size scan files

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-manager#196]
### Description
There is a 256 MB size cap in V8 when loading JSON files. We can get around this issue by loading the JSON with a stream.

### Steps to reproduce
Import a ScanCode JSON file larger than 256 MB

**Expected behavior**
Be able to import a JSON file larger than 256 MB

**Actual behavior**
When a scan is imported, the following error is thrown: `SyntaxError: Unexpected end of JSON input`

**Reproduces how often:** 
Anytime you load a file larger than 256 MB

### Errors in the Developer Tools
None

### System configuration
**Operating System**: MacOS

**AboutCode Manager Version**: v2.0.0

**Comment by pombredanne** [comment]
a way to get a streamable JSON is to use the new ScanCode json-lines output contributed by @JonoYang
