### ISSUE TITLE
No Value Detected dominates packages graph on the dashboard

### ISSUE THREAD

**Issue by majurg** [nexB/aboutcode-manager#197]
### Description
When looking at the dashboard on initial load, the 'Package Types' bar graph is dominated by No Value Detected. 

In the context of packages, it does not make sense to list all the files where a package has been found.

I believe this bar graph should be based on total # of package types as opposed to total # of files. If there is only a single package type (as is the case above), then there would only be a single bar on the graph, at some normalized height. 

### System configuration
**Operating System**: MacOS

**AboutCode Manager Version**: 2.0.1 release

**ScanCode Toolkit Version**: latest develop

For example, plain tarball packages are barely visible:
![screen shot 2017-11-09 at 4 57 00 pm](https://user-images.githubusercontent.com/7485204/32637618-bfbd4614-c56f-11e7-9c05-fd69377e9e00.png)

**Comment by jdaguil** [comment]
I've set No Value Detected to be hidden (de-selected) by default. If one wants to see the No Value Detected breakdown, it can be shown by selecting the value in the legend.
