### ISSUE TITLE
Add "header" information to Conclusions export file

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#198]
The export file for Conclusions should have a "header" data section similar to a ScanCode file with information like notice, the version of ABC Manager, date created, etc.  - Something like:

"aboutcode-manager_notice":"Exported from AboutCode Manager ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nAboutCode Manager should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nAboutCode Manager is a free software analysis application from nexB Inc. and others.\nVisit https://github.com/nexB/aboutcode-manager/ for support and download.",
"aboutcode-manager_version":"x.y.z",
"aboutcode-manager_options": { }  may be useful  for future use

**Comment by mjherzog** [comment]
Perhaps this should also include the name of the ScanCode JSON file imported into ABCM with attributes like file date and size.

**Comment by jdaguil** [comment]
As discussed with @mjherzog I've added the `notice` and `version` for AboutCode Manager to start. We can make updates in the future based on https://github.com/nexB/aboutcode/issues/7.
