### ISSUE TITLE
Screen real estate is not fully used and scrolling can be weird in the table view

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-manager#2]
![8e6dabd2-37e3-11e6-8143-74da09e84ce9](https://cloud.githubusercontent.com/assets/4239800/20122024/a0f2adda-a5c9-11e6-9661-325df3b6feef.png)
As you can see there is a lot of white space on left, right and bottom. I would expect the scroll bar of the main table block to be the ones of the whole window and that table to fill in the space

**Comment by majurg** [comment]
I also experience this on OSX

**Comment by jdaguil** [comment]
Fixed in #148
