### ISSUE TITLE
Add tooltips to Conclusion label fields

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-manager#207]
### Description
A user may need additional help text with field labels when making conclusions.

### Steps to reproduce
1. Open App
2. Import or open a scan file
3. Navigate to Node View
4. Select node file name top open conclusion form

**Expected behavior**
To be able to get additional information about a field name before filling in field.

**Actual behavior**
There isn't additional information describing the form fields.

<img width="640" alt="screen shot 2017-12-08 at 6 10 03 pm" src="https://user-images.githubusercontent.com/4239800/33791608-23396fbc-dc43-11e7-82f6-969197ab695c.png">

### System configuration
**Operating System**:
MacOS
**AboutCode Manager Version**:
v2.1.0

**Comment by jdaguil** [comment]
@mjherzog Could you provide me the tooltip text for the following field labels:

- Modified
- Feature 
- Purpose

**Comment by mjherzog** [comment]
@DennisClark is the expert on help/tooltips, but here are my suggestions.
Modified - Indicates that the component is a copy of third-party code that has been modified by the product team.
Feature - Identifies a feature or module within the codebase, such as UI or Application and used to group components for reporting within a software inventory or BOM
Purpose - Identifies the purpose or usage of a component, such as Build, Test or Core.
