### ISSUE TITLE
Add visual marker for Components in the Tree View

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#209]
It would very useful in the Tree View to be able to see which records already have an associated Component record.  I am not sure whether an icon or other marker would be best or where it would be located. This Issue is to record the idea for further design consideration.

**Comment by majurg** [comment]
I agree. This is a must have IMO.

**Comment by majurg** [comment]
#310 merged, which contains the initial implementation of Conclusion markers on the JS Tree. 

Color and icon change requests can be handled in separate tickets. 

Closing this.
