### ISSUE TITLE
irregular Dropdown box size if it contains "long" value

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-manager#210]
The width of the dropdown box is changed if it contains a 'long' value when user click it.
![1](https://user-images.githubusercontent.com/4246379/33918268-6936c6a6-dfed-11e7-9561-0526a39532d4.png)
![2](https://user-images.githubusercontent.com/4246379/33918270-69641b6a-dfed-11e7-8168-12545e79fd7a.png)
![3](https://user-images.githubusercontent.com/4246379/33918271-69ab50c0-dfed-11e7-831f-decb9e0157c5.png)

**Comment by jdaguil** [comment]
@chinyeungli I believe this is dupe of https://github.com/nexB/aboutcode-manager/issues/194. An official release with this fix has not been cut yet, but in the meantime you can use this build version with the fix: https://ci.appveyor.com/api/buildjobs/5hv8142rt3wa23um/artifacts/dist%2FAboutCode-Manager-windows-x64-2.1.0.post36.69a4518.zip.

**Comment by chinyeungli** [comment]
thanks.
