### ISSUE TITLE
Filter on file extension returns pattern instead of match

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#223]
### Steps to reproduce
1. Load Scan and select File Extension as visible column
2. Open filter box and select ".c"
3. AbC Mgr displays all rows where File Extension starts with ".c" - .class, .css, .csv, etc.
4. Also tried with ".js" to select JS code files
5. AbC Mgr returns all rows where File Extension starts with ".js" - .json, .jsp etc.

**Expected behavior**  
Should return exact filter match on ".c"

**Actual behavior** 
Returns rows with any File Extension beginning with ".c"
Filter match appears to be progressive - i.e. filter on ".jsp" returns .jsp, .jspf and .jspx

**Reproduces how often:**  100%

Errors in the Developer Tools - None
System configuration: Windows 10
AboutCode Manager Version**: 2.3.0
ScanCode Toolkit Version**: 2.2.1

**Comment by majurg** [comment]
#259 merged. Closing.
