### ISSUE TITLE
Start AboutCode Manager ready-to-use from terminal

### ISSUE THREAD

**Issue by FHantke** [nexB/aboutcode-manager#224]
Hello,
is it possible to start aboutcode-manager from a terminal with parameters like "--input data.json --database data.sqlite" and it sets up a new database from the json data?
The background is I want to write a script I can start, which scans a files with scancode and starts aboutcode -manager after without user interaction.
Thank you!

**Comment by jdaguil** [comment]
Currently, there is not a way to set up a database from the terminal. Can you provide a little more information on your use case? Is this to save time by skipping the step to choose the ScanCode JSON file and create the database? Or is there another reason you wouldn't need user interaction?

**Comment by FHantke** [comment]
You're right, it's just to save time. But if it's not possible don't worry, I just wondered if there is a way.

**Comment by mjherzog** [comment]
@FHantke  the longer term plan also includes allowing you to launch a scan from within AbC Manager
