### ISSUE TITLE
Add the ability to filter on Resources that do not have any provenance clues

### ISSUE THREAD

**Issue by JonoYang** [nexB/aboutcode-manager#235]
We currently cannot filter on Resources that do not have clues. In the case of working with a codebase where the majority of the files contains a license and copyright notice, this feature would make it easy to see which files do not have a license or copyright notice so they could be updated.

**Comment by mjherzog** [comment]
+1 - this would also help investigate stats from the Chart Summary view.

**Comment by pombredanne** [comment]
Note that scancode has the `--only-findings` option to avoid reporting these.

**Comment by majurg** [comment]
#279 merged, closing this.
