### ISSUE TITLE
Ignore only whitespace in search box

### ISSUE THREAD

**Issue by JonoYang** [nexB/aboutcode-manager#240]
When only white space is in the search box, this prevents any results from showing up in the table view because the search function is looking for the sequence of white space exactly. If there is white space in the search box, it should be treated as if there is nothing in the search box.

**Comment by majurg** [comment]
We want to be able to handle 2 cases: 
1) Where whitespace is the only 'value' in the search box
2) where there is leading or trailing whitespace

**Comment by majurg** [comment]
Merged #283, closing this.
