### ISSUE TITLE
Support csv as an import input

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-manager#246]
Since we have the capability to output the scan result to csv format in scancode, the aboutcode-manager should support import csv as an input.

**Comment by pombredanne** [comment]
@chinyeungli I think we should not support this. There are too many things that are "damaged" in the data structure when you convert a tree structure to a flat CSV. To me the CSV output in ScanCode is a one way street that cannot get you back anything that could resemble the original richly structured scan data. We could build a utility to roughly convert a CSV to something that would look like a bit a structure JSON. And this could be done here or in ScanCode... but that would be highly lossy and subject to much errors. Can you elaborate on what would be your use case?

**Comment by majurg** [comment]
@chinyeungli: A few things: The CSV output in aboutcode-manager AFAIK is currently only supported for Conclusion data.

**Comment by mjherzog** [comment]
I agree that export to CSV is a one-way street.

**Comment by majurg** [comment]
Will close this for now.
