### ISSUE TITLE
Where is the CSV export option

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-manager#247]
I am using this release: https://github.com/nexB/aboutcode-manager/releases/download/v2.4.0/AboutCode-Manager-windows-x64-2.4.0.zip

but I don't see the export to csv option.

![abcmgr_file_menu](https://user-images.githubusercontent.com/4246379/39571742-184a2dd8-4eff-11e8-8179-85f3734c7ed7.png)

**Comment by johnmhoran** [comment]
The CSV export button is at the top of the page in the Component Summary View.

**Comment by chinyeungli** [comment]
Thanks.
It means I can only export component data in CSV but not the "raw" data

**Comment by mjherzog** [comment]
Correct - only Conclusions data, not scan data.

**Comment by chinyeungli** [comment]
ok. Thanks for the verification.
