### ISSUE TITLE
Change "Component" to "Name" in Edit Conclusion screen

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#250]
The current Edit Component screen has the label "Component", but that field is shown as only "Name"elsewhere. We should change to Name in the Edit Component screen since the data is neither explicitly for a Component versus a Package. There may be other references to update in the same way.

**Comment by majurg** [comment]
@mjherzog After tweaking some of the view code I have the following:
![screen shot 2018-06-01 at 6 04 50 pm](https://user-images.githubusercontent.com/7485204/40868856-74ad44ce-65c6-11e8-8598-81fb2bfe6bad.png)

I adjusted the default status text a little bit; I can make other adjustments if necessary.

**Comment by majurg** [comment]
Merged #256, closing this.
