### ISSUE TITLE
Make "All" an explicit value in Filters

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#251]
The Filter drop-downs currently have two placeholder values in addition to the specific values that are present in the scan date:
1. Blank/null is shown to indicate all records
2. "Has a value" is shown to indicate all records with any non-null value

Showing blank/null for #1 is confusing from a UI perspective and also makes it hard to track which columns have an active filter. We need to somehow show a value of "All" or similar to indicate that the current view shows all rows in the Table View.

**Comment by majurg** [comment]
#258 merged. Closing this.
