### ISSUE TITLE
Add visual marker for Packages

### ISSUE THREAD

**Issue by pombredanne** [nexB/aboutcode-manager#26]
ScanCode collects packages and they are a natural break and summarization point where I want to focus my review first and eventually create a component at that level. 
As a start, I would like to have a visual indication that a node is a package (as reported by ScanCode as being a package)

**Comment by Rishav159** [comment]
I want to work on this issue.  I have successfully deployed the app locally. Can you guide me on how I should start?

**Comment by Rishav159** [comment]
@pombredanne Yes, it does! I will go through the files to figure out ways to implement this. Would you be available if I have a doubt or get stuck?
Thanks in advance.

**Comment by pombredanne** [comment]
we will sure be available. Feel free to submit a pull request early even if this is work in progress ass it will make the review by @jdaguil much easier.

**Comment by Rishav159** [comment]
@pombredanne Okay sure. I will try to understand the underlying working of the app and start working on this issue as soon as possible.

**Comment by pombredanne** [comment]
@Rishav159 Do not hesitate to ask questions here :) Small code changes one at a time are always easier to review and swallow...

**Comment by Rishav159** [comment]
@pombredanne Thanks for this kind of support! I am really glad.
Okay so as I can understand till now, the app takes in a JSON file generated by the scancode-toolkit as input and shows it in different views. Trying to understand the JSON file, It contains a key 'files' with an array of information of the all the files/directory in the folder. 
Now how do I identify a package node? Is it related to the 'packages' key ? The given sample JSON does not have any package maybe ?
Thanks

**Comment by pombredanne** [comment]
@Rishav159 to get some packages scanned, download a few RPMs and npms in a directory and scan the directory with `scancode --package --license --copyright ...`. You will see detected packages as an array under the `"packages": []`

**Comment by Rishav159** [comment]
@pombredanne Okay. I will try that.

**Comment by Rishav159** [comment]
@pombredanne I have added a (P) identifier at the end of the files that include packages.
You can find the changes [here](https://github.com/Rishav159/aboutcode-manager/commit/a0e1ebae12a08d65bcd4e487616be2ef41d5bb8c) 
Should I create a pull request?

**Comment by pombredanne** [comment]
@Rishav159 Thanks! and yes , please create a PR. These are best for review

**Comment by Rishav159** [comment]
@pombredanne Okay I will create a PR. I have only updated the node view for now. Updating the tree view is a little confusing as I have no experience with the Jstree. I will trying digging deep into it.

**Comment by Rishav159** [comment]
@pombredanne I have changed the identifier to make the text-background color of filenames to green for files which has packages. Creating a new PR. Please review.

**Comment by majurg** [comment]
merged #309, closing this.
