### ISSUE TITLE
Filter selected in Chart View remains active after navigation but Table View filter displays 'All'

### ISSUE THREAD

**Issue by johnmhoran** [nexB/aboutcode-manager#265]
### Steps to reproduce
1. Open a sqlite file with license, copyright etc. data.
2. Navigate to the Chart Summary View, select a node in the tree on the left, and in the attribute dropdown on the right, select `License Key` as the attribute.  This results in the display of a horizontal bar chart displaying the options (if any) from which the user can choose a value.
3. From the horizontal bar chart, select a value by clicking the relevant bar.  Doing so leaves the treeview open on the left (with your selected node still selected), and the bar chart is replaced by the Table View, filtered by your selected value -- as indicated by the value in the filter dropdown box at the base of the relevant column (in this example, `License Key`).
4. Use the treeview to navigate to another node (directory or file).  In the Table View, your previously-selected filter and value remain in effect, but the value displayed in the filter dropdown box has been changed to `All`.  This is the case when you navigate back to your initially-selected tree node as well.

**Expected behavior**
One of two things: keep the filter in effect and keep displaying the filtered value, or reset the filter and the display to `All`.

**Actual behavior**
As above: the filter remains in effect but `All` is displayed in the filter dropdown box.

**Reproduces how often:** 
100% so far (though just a few test runs just now).

### Errors in the Developer Tools
0 errors displayed/logged.

### System configuration
**Operating System**: Windows 10 Pro version 1803 64-bit

**AboutCode Manager Version**:  2.4.1

**ScanCode Toolkit Version**:  2.9.2

### Additional Information
Any additional information, configuration, or data that might be necessary to reproduce the issue. (i.e. screenshots and/or GIFs)

**Comment by johnmhoran** [comment]
The behavior described above also occurs if -- rather than selecting the filter and value via the Chart Summary View -- I simply use the Tree/Table View and select the filter/value using the filter dropdown box at the base of the relevant column of the Table View.  In that case, too, the selected filter/value remains in effect as I use the Tree to navigate, but the value displayed changes to `All` with the first step of my navigating via the Tree.

**Comment by majurg** [comment]
#269 fixes this. Closing.
