### ISSUE TITLE
Show Tree View in other views

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#267]
With current version 2.4.1 the TreeView is shown on the left for the Chart Summary View and the Table View, but not for the Dashboard View or Component Summary View. It makes sense to offer the Tree View on the left for all Views since the Tree View shows you the codebase you are working with and it is the easiest way to navigate files and directories. This will also allow you to "keep your place" relative to the codebase as you move among directories and files which is already the case for the Table and Chart Summary Views.

The specific enhancement is to add the Tree View for the Dashboard and Component Summary Views with the same navigation approach as the Table View - i.e the window on the right will show you data related to your current selection in the Tree View

This issue does not deal with the Edit Component window, but an assumption for simplicity could be that you can invoke Edit Component from the Tree View regardless of which other View that is on the right. It is probably not very useful to Edit Component from the Chart Summary View (or Dashboard View) but not clear that it would cause any harm.

See also #268 for some View naming changes that will likely apply before this enhancement.

**Comment by johnmhoran** [comment]
@mjherzog See also issue #128 (add links in Component Summary View) (and note one of Jillian's comments: "In particular, we add an onClick to the html element surround the text. As a side note, we might want to consider having the jsTree displayed in all of the views. This might mitigate part of the problem.").

**Comment by majurg** [comment]
#305 merged, closing this.
