### ISSUE TITLE
Refine Column visibility options

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#272]
The current set of Column Visibility options are primarily organized by data entity rather than function. We have:
- Origin info
- Copyright info
- License info
- Package info
plus Show All, Hide all and the default set of columns from the Column Visibility button itself.

It probably makes sense to refine these options and consider adding some that are more "task" focused and revisit the columns for the current Info options.

1. Origin Info is an example of more task focus where you show the primary Origin clues from a scan with -clip scan options.  For Origin Info it would be good to add at least File Type and perhaps Language to help an analyst evaluate whether a row represents code

2. Add File Info to be used when you are just looking at basic codebase structure - corresponding to the-i scan option. Likely columns would be File Name, File Extension, File Size, File Type and Language.

3. For License Info, simplify by removing the 3 URLs (Homepage, Text and Reference) since these are all derived data.

The current default set of columns is: Copyright Statements, License Short Name, File Name, File Size, SHA1 and File Type - I suggest that we drop SHA1 since it is quite wide as a column and it seems unlikely that is very helpful for user review (more often used for automated matching/comparison).

We could also consider removing:
- "Info" from the buttons since it seems redundant and we will likely want to add more buttons over time.
- Rename "Column visibility" to just "Columns"

**Comment by majurg** [comment]
I agree with this proposal. @mjherzog Should we default to File Info columns to begin with? File Info columns should always be present and may reduce some of the confusion when a loading a File Info only scan in ABCM as there will not be unfilled columns like License and Copyright columns.

**Comment by mjherzog** [comment]
That could make sense to keep it simple and pretty easy to explain.  One theme for me is combining Origin info with File Info to quickly see what rows are most relevant (which was my first idea for the new default set of columns). Simple is good

**Comment by mjherzog** [comment]
I think that we should set default display to FileInfo with:
- Type (for filtering out directories)
- File Name (always a classic)
- File Extension (?)
- File Size
- MIME Type
- File Type
- Language (?)

These would give us a quick overview of what you are looking at from a Fileinfo perspective. I left out SHA1 because it takes up a lot of horizontal space and not likely that you can do much with it from UI perspective, 

Also we might want to remove the URLs from License info column set - these are typically wide fields so let the user add them in if desired.

**Comment by majurg** [comment]
@pombredanne @JonoYang @DennisClark 

Any specific thoughts or suggestions you might want to add?

**Comment by pombredanne** [comment]
@majurg I may provide extra feedback once you have a first pass... It looks decent with your planned changes

**Comment by mjherzog** [comment]
For Origin it would be useful to have some file info. As a practical matter Type might be most important so that you can quickly filter out directories. It would also be useful to have one clue about file content where File Type is probably the best that we currently have.

**Comment by majurg** [comment]
#314 merged, closing this.
