### ISSUE TITLE
Provide Table View with ability to display just those records with no (null?) value

### ISSUE THREAD

**Issue by johnmhoran** [nexB/aboutcode-manager#276]
In the Chart Summary View, if the user selects `File Extension`, for example, and then selects the option where no value is listed (representing a directory/file with no extension), the value shown as selected in the Table View is "All" and all the relevant records (with and without extensions) are displayed -- not what one would expect.  If the user then activates the filters (by clicking `Activate Filters`) and examines the available options, there's no option for files with no extension.  I suspect it could be useful to add this filtering/display capability to the Table View filters.

**Comment by johnmhoran** [comment]
@majurg  I agree -- as we already provide, e.g., for `License Expressions`, `Package Authors Name` and others.   You mentioned that this would be related to an already-opened issue -- were you referring to issue #235?

**Comment by majurg** [comment]
Yes that is the one.

**Comment by johnmhoran** [comment]
Thanks @majurg .

**Comment by majurg** [comment]
#279 merged, closing this.
