### ISSUE TITLE
'Has a Value' filter sometimes displays empty copyright attributes

### ISSUE THREAD

**Issue by johnmhoran** [nexB/aboutcode-manager#277]
When I select the `Has a Value` filter for one of the copyright attributes in the Table View, sometimes (not yet sure how often or if always) a row is displayed with no value for the filtered attribute.  Two examples I've seen: 
* select `Has a Value` for `Copyright Authors` -- row is displayed where that column is empty but a value is present in `Copyright Statements`, `Copyright Holders` and the start and end line columns.
* select `Has a Value` for `Copyright Statements` -- row is displayed where that column is empty but a value is present in `Copyright Authors` and the start and end line columns (`Copyright Holders` is also empty).

Seems like the `Has a Value` filter for copyright attributes might be examining the entire set of nested key-value pairs inside the scan's `copyrights` value, e.g.,

```
      "copyrights": [
        {
          "statements": [],
          "holders": [],
          "authors": [
            "Noah Friedman <friedman@prep.ai.mit.edu>"
          ],
          "start_line": 2,
          "end_line": 5
        }
      ],
```

(These observations are based on scans of `e2fsprogs-1.44.2` created with ScanCode v2.9.2.)

**Comment by johnmhoran** [comment]
This behavior also seems to affect the code I'm developing for issue #235 -- adding a `Has no Value` filter option.  For example, 
* select `Has no Value` for Copyright Statements -- Table View does not display row where that column is empty but a value is present in Copyright Authors and the start and end line columns.

(BTW, the path for this example is `e2fsprogs-1.44.2/config/mkinstalldirs`.)

**Comment by majurg** [comment]
#299 merged, closing this.
