### ISSUE TITLE
Tests fail on Windows 10 due to 'CRLF' line endings

### ISSUE THREAD

**Issue by johnmhoran** [nexB/aboutcode-manager#278]
Running Visual Studio Code on Windows 10, the test suite (initiated with `npm test`) now displays hundreds of lines of errors, e.g.,  `2:26  Expected linebreaks to be 'LF' but found 'CRLF' - linebreak-style`.  

Initial research suggests this arises from the use of ESLint and the following setting in `.eslintrc.json`:
```
. . .
    "rules": {
        "indent": [
            "error",
            2
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
. . .

```
Changing `unix` to `windows` resolves all of the errors -- and all tests pass -- but this is not a practical solution because of its expected adverse impact on non-Windows development environments.

**Comment by johnmhoran** [comment]
@majurg  Given our `linebreak-style` setting, we may want to explore [this suggestion from the folks at ESLint](https://eslint.org/docs/rules/linebreak-style#using-this-rule-with-version-control-systems): 

> create a `.gitattributes` file and add `*.js text eol=lf` "to prevent git from converting linebreaks in .js files".

**Comment by majurg** [comment]
commit 495af3f1ed8ea99314e44b5390ee63a0a7ed58c3 addresses this for windows hosts, using https://gist.github.com/RadValentin/dd8b9d70448413301e9a274ed54661a5 as a guide.
