### ISSUE TITLE
Make "No Value Detected" on the bar-chart clickable 

### ISSUE THREAD

**Issue by majurg** [nexB/aboutcode-manager#280]
Now that we have "Has No Value" as a valid filter option, we need to hook this into the bar chart.

So, when the bar chart lists "No Value Detected" we need this to have the same behavior as a typical bar-chart drill down value: Open up the Clue table with "Has No Value" filter active and selected.

**Comment by johnmhoran** [comment]
@majurg  I seem to have the `No Value Detected` bars properly clickable now, but I've noticed that the count for that value is at least occasionally inaccurate.  Part of the problem looks to be related to [excluding](https://github.com/nexB/aboutcode-manager/blob/develop/assets/app/js/controllers/aboutCodeBarChart.js#L88-L91) files of type `directory` in `aboutCodeBarChart.js`, but some inaccuracies persist even after I modify that code.  

That behavior is not clearly part of the current issue and perhaps merits opening a separate issue.  I'll examine more closely and provide details.

**Comment by majurg** [comment]
@johnmhoran Yes open a new ticket for that issue.

If your solution is working for the current issue, open PR whenever you are ready.

**Comment by majurg** [comment]
#281 has been merged. Closing this.
