### ISSUE TITLE
Store Scan input in a database

### ISSUE THREAD

**Issue by DennisClark** [nexB/aboutcode-manager#31]
Evaluate open source javascript-friendly databases (for example, http://www.taffydb.com/ , to store scan data in an ABC-compatible format.

**Comment by DennisClark** [comment]
Also research this one: 
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API  
which is apparently a feature of electron.

**Comment by jdaguil** [comment]
Also done in 6a9d325: 
* Added a new DB for nodeview.
* Added License, Copyright, Email, Url, and Packages model
