### ISSUE TITLE
Remove built-in samples data

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#34]
AboutCode Manager should not display anything until you open a ScanCode file.  The current display of the  "built-in: samples directory confusing to first-time users. In the near-term, we can provide a file samples.json with the same data and advise a new user to use that if they have not run any scans.

Longer term, we should provide a set of "sample" ScanCode files with the application so that a new user can see examples from real code and we can use these examples for test data. I will come up with a list of good example projects with key guideline that they load quickly and show interesting data and license notice patterns.

**Comment by jdaguil** [comment]
Removed this behavior in #31
