### ISSUE TITLE
Add fuse 2.9.1 Scan data to /samples and document

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#35]
We want to add several (5-6) ScanCode data files to the /samples for ABC Manager starting with jfuse 2.9.1 as an example of a Linux userspace application written in C.  This task is to:

- Add a current ScanCode JSON file for fuse 2.91. to the /samples directory
- Create a new section in the README for Samples which should include information such as a brief description of the Package, link to download it and documentation of the version ScanCode and options used to create the JSON file.

For each new Sample Scan, we will need to follow the same process and plan for updating the Samples for new releases of ScanCode Toolkit.

**Comment by mjherzog** [comment]
We want the /samples/ files to be stored and versioned in GitHub to ensure that the sample scan format matches the corresponding version of ABC Manager, but we do not need to include them in the Distribution.  Rather ABC Manager Help should point to the README with links to the sample scan files.

**Comment by mjherzog** [comment]
Update with new version with Root.

**Comment by johnmhoran** [comment]
Closing Issues #35-#38 -- addressed by Issue #46 and Pull Request #51.
