### ISSUE TITLE
Add zlib 1.2.11 as separate Sample Scan

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#36]
We currently have zlib as part of a composite Sample scan file.  This task is to add a separate scan for teh complete zlib 1.2.11 package from http://zlib.net/zlib-1.2.11.tar.gz.  zlib is one of the most popular open source packages with a few license exceptions - notably the GPL-licensed ADA code.

**Comment by mjherzog** [comment]
Update with new version with Root.

**Comment by johnmhoran** [comment]
Closing Issues #35-#38 -- addressed by Issue #46 and Pull Request #51.
