### ISSUE TITLE
Add Google Protobuf 3.0.0 as Sample Scan

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#37]
Add Google Protobuff as a Sample project.  This is a very popular package and it features code from many languages - csharp, java, python, ruby, etc. You will need to download as Zip from https://github.com/google/protobuf/tree/v3.0.0

**Comment by mjherzog** [comment]
Update with new Sample Scan with Root

**Comment by johnmhoran** [comment]
Closing Issues #35-#38 -- addressed by Issue #46 and Pull Request #51.
