### ISSUE TITLE
Add rapidjson 1.1.0 as Sample Scan

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#38]
Add rapidjson 1.1.0 as  a Sample project. This is "A fast JSON parser/generator for C++ with both SAX/DOM style API" and so an example of C++.  There are some large JSON test files which may slow down the scan a bit.  You will need to download as Zip from https://github.com/miloyip/rapidjson/tree/v1.1.0

**Comment by mjherzog** [comment]
Update with Sample Scan including Root.

**Comment by johnmhoran** [comment]
Closing Issues #35-#38 -- addressed by Issue #46 and Pull Request #51.
