### ISSUE TITLE
Display folders above files (if any) in jsTree

### ISSUE THREAD

**Issue by johnmhoran** [nexB/aboutcode-manager#41]
The folders are displayed at the bottom of the jsTree listing, after the files (if any) are displayed.  Since the more traditional display is folders first, some users may not see folders where expected and conclude they’re not available.

**Comment by Rishav159** [comment]
@johnmhoran Hello, Can I work on this issue? I was already thinking about doing this and wrote a sort function for the same before seeing you self-assigned it. 
I have also fixed the icon labels for the folders not showing unless clicked upon. It seems like the scancode-toolkit has some problems generating correct jstreeData. All the "types" key of the nodes was set to "file" even if it is a directory.

**Comment by johnmhoran** [comment]
Thanks, @Rishav159.  I’m already working on this issue (and the folder icons), but you’re certainly welcome to submit a pull request.

**Comment by Rishav159** [comment]
@johnmhoran I have made a pull request. Please review.

**Comment by Rishav159** [comment]
@johnmhoran Can you help me by telling me why the travis builds are failing ? I couldn't understand it.
Thanks.

**Comment by majurg** [comment]
@johnmhoran @jdaguil I like this suggestion. I often have trouble distinguishing between files and folders in the tree view, and this would go a long way to help. 

Additionally, perhaps listing the folder icons in a different color (like the way `ls` on a unix machine) could be added as well to further distinguish between files and directories.
