### ISSUE TITLE
Warning when building on Linux

### ISSUE THREAD

**Issue by pombredanne** [nexB/aboutcode-manager#48]
As reported by an anonymous good soul on on IRC we get these messages when running `npm install` on a fresh repo (here using node  `node-v6.10.1-linux-x64.tar.xz` on Ubuntu 14):
```
npm WARN aboutcode-manager@1.1.0-beta.3 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.12 (node_modules/nodemon/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```
This is on the develop branch.
The app starts fine otherwise.

**Comment by nitkul** [comment]
Are you sure this is not a 'symlink' error?
Running `sudo ln -s /usr/local/bin/nodejs /usr/bin/node` and then `npm install` works for me.

**Comment by pombredanne** [comment]
@nitkul I guess it could be... now we would typically not depend on a global install of node. So an install requiring a sudo would typically not work out for us.  And how could skipping optional deps be related to symlinks?

**Comment by nitkul** [comment]
@pombredanne this is not related to global install: symlink basically reinforces the command `node` on `nodejs`. However, I do see your point: for me, the 'SKIPPING OPTIONAL DEPENDENCY' messages did not appear... and I don't see how symlink corrected that!

**Comment by jdaguil** [comment]
@pombredanne This appears in the initial development setup for windows and linux. It's only a warning not a terminating error.
