### ISSUE TITLE
AboutCode Manager should be able to open data.json files from ScanCode html-app format

### ISSUE THREAD

**Issue by JonoYang** [nexB/aboutcode-manager#49]
In some cases, auditors are given a ScanCode scan in html-app format, where the scan data is in `data.json`, which is in slightly different format than the standard ScanCode JSON output.

**Comment by mjherzog** [comment]
This may not be necessary since we plan to deprecate the html-app format.

**Comment by pombredanne** [comment]
@JonoYang I think this is not warranted. The html-app format will eventually go away... and if not, it will and should use the standard JSON output instead. I am closing this for now.
