### ISSUE TITLE
Fix display of “Electron” title rather than “AboutCode Manager” on Darwin/OS X

### ISSUE THREAD

**Issue by johnmhoran** [nexB/aboutcode-manager#61]
The custom menu is now displayed on Darwin/OS X in development mode but the menu displays the default `Electron` title rather than `AboutCode Manager`.  This problem is not encountered on Windows or Linux, both of which now display the custom menu properly in development mode.

**Comment by pombredanne** [comment]
Is this only in development or also when you install?
If is this in development only, let's close this. Closing!
