### ISSUE TITLE
Add missing ScanCode attributes to corresponding models

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-manager#68]
### License Model
- matched_rule

### Copyright Model
- author

### Package Model
- name
- version
- summary
- description
- payload_type
- authors
- maintainers
- contributors
- owners
- packagers
- distributors
- vendors
- keywords
- keywords_doc_url
- metafile_locations
- metafile_urls
- homepage_url
- notes
- download_urls
- download_sha1
- download_sha256
- download_md5
- bug_tracking_url
- support_contacts
- code_view_url
- vcs_tool
- vcs_repository
- vcs_revision
- copyright_top_level
- copyrights
- asserted_licenses
- legal_file_locations
- license_expression
- license_texts
- notice_texts
- dependencies
- related_packages

**Comment by jdaguil** [comment]
Merged `68-add-missing-attributes` into `develop`. Keeping the issue open for additional possible updates based on https://github.com/nexB/scancode-toolkit/issues/617 and https://github.com/nexB/scancode-toolkit/issues/618

**Comment by pombredanne** [comment]
@jdaguil Let's have a review together for this and #81

**Comment by jdaguil** [comment]
Reviewed and merged into `develop`
