### ISSUE TITLE
Add option to invoke Conclusions View from Directory Tree

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#80]
In cases where the Table View is easier to use than the Conclusions View, it would be helpful to be able to invoke the Conclusions window from the Tree View by right-clicking on the directory or file. Although the current Conclusions View shows the same License and Copyright data you would normally use to record a Conclusion about License and Copyright, the Table View offers additional data that is important for making your Conclusions in many cases.
The current Conclusions View could be renamed to  "Node View" or similar.

**Comment by jdaguil** [comment]
This is merged into `develop`
