### ISSUE TITLE
Node view rotation

### ISSUE THREAD

**Issue by majurg** [nexB/aboutcode-manager#93]
I would like to be able to rotate the tree growth direction when viewing results in the node view. 

Currently, the node view grows the file tree horizontally, expanding to the right. In many cases, large flatter codebases would be better viewed if the file tree grew top-down.

**Comment by jdaguil** [comment]
We do have an option for ['top-to-bottom'](https://github.com/nexB/aboutcode-manager/blob/e6686c0358dc8536305d9c38e3bbc0ed4ad90f5e/assets/app/js/controllers/aboutCodeNodeView.js#L151) orientation; however, the spacing between nodes doesn’t work well so there's a lot of overlap. The spacing in node view between nodes is not very sophisticated (iirc it’s just a hard coded offset), and it still needs more work.

**Comment by majurg** [comment]
Per #255, the Node View has been depreciated. Closing this ticket.
