### ISSUE TITLE
Node View: blank spaces where license and copyright info would be

### ISSUE THREAD

**Issue by majurg** [nexB/aboutcode-manager#94]
In the node view, with 'filename' 'license' and 'copyright' tags selected at the top, Nodes with no copyright or license information are spaced as if they did contain such information. 

This make the node view awkward and nodes appear more spread out, unnecessarily eating up screen real estate.

This behavior was discovered running the development branch on macOS.

**Comment by jdaguil** [comment]
This would probably be difficult. Currently, we rely on D3's tree algorithm to position each node. It spaces every node evenly. I couldn't find a way to have custom spacing per node.

**Comment by majurg** [comment]
Per #255, the Node View has been depreciated. Closing this ticket.
